### ISSUE TITLE
How to contribute to front end for this project? Where is the demo? 

### ISSUE THREAD

**Issue by raunakhajela** [tbhaxor/node-dnstools#4]

**Comment by tbhaxor** [comment]
All the modules are separately defined in `.js` file and import in `index.js`

The current version is using `https` node module to accomplish the functionality and i want it to function for browser as well like [axios](https://github.com/axios/axios) uses *http*/*https* when used in nodejs and *XMLHttpRequest* when used in browser

**Comment by tbhaxor** [comment]
Closing this
